### ISSUE TITLE
Knowledge Base

### ISSUE THREAD

**Issue by Lunalorla** [Lunalorla/DI-CA_Icon-2021-2022#2]
**Knowledge Base:**
-https://github.com/Midorilly/IBM-AP

-https://mnoorfawi.github.io/pytholog/How%20pytholog%20works/ (link libreria pytholog)

-http://www.cs.trincoll.edu/~ram/cpsc352/notes/prolog/factsrules.html (prolog)

**To do list:**

-creare una lista accurata di fatti e regole
[-Fatti: 1. richiesta della presenza di un gioco nel catalogo 2. confronti con info legate ai giochi (casa produttrice, categoria...)
[-Regole semplici: 1. richieste su giochi o gioco con precise caratteristiche semplici]
[-Regole complesse: 1. richieste su giochi con un determinato prezzo, genere e rating (?) come vincoli (possibile limitazione del risultato e possibili altri vincoli) 2. calcolo e confronto della qualità di due giochi dati in input dall'utente presenti nella knowledge base]

-creare la knowledge base partendo dal file del dataset (vedi codice eleonora)
[-inserimento di fatti e regole prendendo le componenti dal file .cvs letto tramite la libreria pandas]

-creare il main di interazione con l'utente per le query della kb

**Comment by Lunalorla** [comment]
`data['Positivity_quote'] = steam_data['positive_ratings'] // steam_data['negative_ratings'] #unione dei due tipi di ratings in uno solo`

**Comment by RobertoDimatteo** [comment]
[kb fatti.txt](https://github.com/Lunalorla/DI-CA_Icon-2021-2022/files/9396700/kb.fatti.txt)

Lista di alcuni possibili fatti e regole

**Comment by Lunalorla** [comment]
[regole e fatti aggiuntivi.txt](https://github.com/Lunalorla/DI-CA_Icon-2021-2022/files/9601394/regole.e.fatti.aggiuntivi.txt)

Documento con regole e fatti aggiuntivi per le modifiche da porre alla KB

**Comment by Lunalorla** [comment]
![image](https://user-images.githubusercontent.com/61514798/191566047-7f8614ff-f3f6-49f3-b514-8458b78c0daa.png)
 formula variazione percentuale

**Comment by Lunalorla** [comment]
![image](https://user-images.githubusercontent.com/61514798/191586013-32488bd9-eca1-4f1d-b22a-adce6bd4a06f.png)

**Comment by Lunalorla** [comment]
[regole.e.fatti.aggiuntivi.txt](https://github.com/Lunalorla/DI-CA_Icon-2021-2022/files/9619618/regole.e.fatti.aggiuntivi.txt)
Modifica alla lista di regole da aggiungere
